[Definition]

# Match pre-auth SSH failures
failregex = ^.*sshd(-session)?\[\d+\]: (Timeout before authentication|Unable to negotiate|Connection reset|banner exchange: invalid format).* from <HOST>
ignoreregex =
